version = 0.1
[default.deploy.parameters]
stack_name = "url-shortener-9faf053d"
resolve_s3 = true
s3_prefix = "url-shortener-9faf053d"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
