AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  URLTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: URLTable
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  ShortenFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/
      Handler: shorten.handler
      Runtime: nodejs18.x
      Events:
        ShortenApi:
          Type: Api
          Properties:
            Path: /shorten
            Method: post
      Environment:
        Variables:
          TABLE_NAME: URLTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: URLTable

  RedirectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/
      Handler: redirect.handler
      Runtime: nodejs18.x
      Events:
        RedirectApi:
          Type: Api
          Properties:
            Path: /{id}
            Method: get
      Environment:
        Variables:
          TABLE_NAME: URLTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: URLTable